import Link from "next/link";

import { FinancialStatusBadge, FinancialTypeBadge } from "@/components/financial/financial-badges";
import { formatCivilDate, formatEuro } from "@/components/financial/financial-format";
import type { FinancialEntry } from "@/types/financial";

export function FinancialList({ items, hasFilters }: Readonly<{ items: FinancialEntry[]; hasFilters: boolean }>) {
  if (items.length === 0) return <section aria-labelledby="financial-empty-title" className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><h2 id="financial-empty-title" className="text-lg font-semibold text-slate-950">{hasFilters ? "Nenhum resultado encontrado" : "Nenhuma movimentação encontrada"}</h2><p className="mt-2 text-sm text-slate-600">{hasFilters ? "Não existem movimentações para os filtros atuais." : "Registe a primeira movimentação financeira."}</p><Link href={hasFilters ? "/financeiro" : "/financeiro/novo"} className="mt-6 inline-flex min-h-11 items-center rounded-lg bg-blue-700 px-4 text-sm font-semibold text-white">{hasFilters ? "Limpar filtros" : "Nova movimentação"}</Link></section>;
  return <><div className="space-y-3 md:hidden">{items.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950"><Link href={`/financeiro/${item.id}`} className="hover:text-blue-700 hover:underline">{item.description}</Link></h2><div className="mt-3 flex flex-wrap gap-2"><FinancialTypeBadge type={item.type} /><FinancialStatusBadge status={item.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-600">Valor</dt><dd className="mt-1 font-semibold text-slate-950">{formatEuro(item.amount)}</dd></div><div><dt className="text-slate-600">Referência</dt><dd className="mt-1 text-slate-900">{formatCivilDate(item.reference_date)}</dd></div></dl></article>)}</div><div className="hidden overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm md:block"><div className="overflow-x-auto"><table className="w-full min-w-[58rem] border-collapse text-left"><caption className="sr-only">Movimentações financeiras</caption><thead className="bg-slate-50"><tr>{["Descrição", "Tipo", "Status", "Valor", "Referência", "Vencimento", "Categoria"].map((label) => <th key={label} scope="col" className="h-13 px-5 text-xs font-semibold uppercase tracking-wide text-slate-600">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id} className="hover:bg-slate-50"><th scope="row" className="px-5 py-4 text-sm font-semibold text-slate-950"><Link href={`/financeiro/${item.id}`} className="hover:text-blue-700 hover:underline">{item.description}</Link></th><td className="px-5 py-4"><FinancialTypeBadge type={item.type} /></td><td className="px-5 py-4"><FinancialStatusBadge status={item.status} /></td><td className="px-5 py-4 text-sm font-semibold text-slate-900">{formatEuro(item.amount)}</td><td className="px-5 py-4 text-sm text-slate-700">{formatCivilDate(item.reference_date)}</td><td className="px-5 py-4 text-sm text-slate-700">{formatCivilDate(item.due_date)}</td><td className="px-5 py-4 text-sm text-slate-700">{item.category ?? "—"}</td></tr>)}</tbody></table></div></div></>;
}
